# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

psvr_ucenter:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ucenter
  pool: 5
  username: root
  password: "jknlff8-pro-17m7755"
  socket: /tmp/mysql.sock

sub_cnu: &sub_cnu
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ktv_sub_cnu
  pool: 5
  username: root
  password: "jknlff8-pro-17m7755"
  socket: /tmp/mysql.sock
sub_cnu_dev:
  <<: *sub_cnu

sub_ibeike: &sub_ibeike
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ktv_sub_ibeike
  pool: 5
  username: root
  password: "jknlff8-pro-17m7755"
  socket: /tmp/mysql.sock
sub_ibeike_dev:
  <<: *sub_ibeike

sub_buaa:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ktv_sub_buaa
  pool: 5
  username: root
  password: "jknlff8-pro-17m7755"
  socket: /tmp/mysql.sock
