defaults: &defaults
  host: '0.0.0.0'
  autocreate_indexes: false
  allow_dynamic_fields: true
  include_root_in_json: false
  parameterize_keys: true
  persist_in_safe_mode: false
  raise_not_found_error: true

development:
  <<: *defaults
  host: '0.0.0.0'
  database: ktv_sub

test:
  <<: *defaults
  database: ktv_test

# set these environment variables on your prod server
production: &productions
  <<: *defaults
  host: '0.0.0.0'
  database: ktv_sub

staging:
  <<: *productions

