defaults: &defaults
  host: '0.0.0.0'
  autocreate_indexes: false
  allow_dynamic_fields: true
  include_root_in_json: false
  parameterize_keys: true
  persist_in_safe_mode: false
  raise_not_found_error: true

sub_cnu: &sub_cnu
  <<: *defaults
  database: ktv_sub_cnu
sub_cnu_dev:
  <<: *sub_cnu
  
sub_ibeike: &sub_ibeike
  <<: *defaults
  database: ktv_sub_ibeike
sub_ibeike_dev:
  <<: *sub_ibeike
  
sub_buaa:
  <<: *defaults
  database: ktv_sub_buaa
