defaults: &defaults
  host: '127.0.0.1'
  
sub_cnu: &sub_cnu
  <<: *defaults
  port: 6380
sub_cnu_dev:
  <<: *sub_cnu

sub_ibeike: &sub_ibeike
  <<: *defaults
  port: 6381
sub_ibeike_dev:
  <<: *sub_ibeike

sub_buaa: &sub_buaa
  <<: *defaults
  port: 6382
sub_buaa_dev:
  <<: *sub_buaa
