default: &defaults
  wendaoguangchang_threshold: 30
  wendaoguangchang_ans_threshold: 1
  # 网站名称
  app_name: "Kejian.TV"
  # 页脚版权
  foot_html: "Copyright © Kejian.TV All Rights Reserved."
  # 网站的域名
  domain: "kejian.tv"
  apidomain: "api.kejian.tv"
  # 配置图片的域名
  upload_url: "/uploads"
  # 设置管理员，在下面填写需要设置为管理员的用户 email
  admin_emails: ['pmq2001@gmail.com']
  email_sender: '"Kejian.TV 课件交流系统" <kejian.tv@gmail.com>'

  smtp_username: 'wendao@kejian.tv.cn'
  smtp_password: 'user_0104'

  # aws_access_key_id: 'your aws access_key_id'
  # aws_secret_access_key: 'your aws secret_access_key'
  # 是否开放注册
  allow_register: true
  # 题被多少次 spam 隐藏
  ask_spam_max: 8
  # 解答被多少次 spam 会删除线
  answer_spam_max: 8
  google_analytics_id: "UA-22413508-1"
  spam_words: /敏感词1|敏感词2/
  wendao_domain_name: "kejian.tv"
  error_tracker_url: 'http://etsrv.dev.kejian.tv/ErrorTrackerRestfulImpl.svc/adderrorlog'
  error_tracker_enabled: false
  # Kejian.TV开放API的信任客户端，以下客户端可以在用户不知情的情况下随意获得任何用户的授权
  # 请填写client_id.
  trusted_client_ips: ['127.0.0.1', '0.0.0.0']
  hexdigest_pass: '287dshfkjdhFF09GG&*^^#!*&Hjkh%&!^&!G9787h8230*&T@@&*@(*JJHJHGGG)'
  snda_id: '7HDL3HVT04F5RF6BRW90BJUXH'
  snda_key: 'MzdmYTkzNjMtYTViZi00NWY4LWI4MTMtZGE0OWJlZTIxMWMw'
  user_qingqiu_id: 72
  course_qingqiu_id: 2116
  topic_qingqiu: '领域请求'
  dz_authkey: '0b7310esiKtBIrpX'
  dz_cookiepre: '6tce_'
  dz_cookiepath: '/'
  ktv_courseware_id: '500f9970e13823796a000002'
  ktv_domain: kejian.tv
  ktv_simple_domain: "kejian.tv/simple"
  ktv_search_domain: "search.kejian.tv"
  root_topic_id: '501137a1e138236528000016'
  zuozheqingqiu_id: '5010da4ce138231d4300004f'
  google_analytics_key: UA-28971136-1
  # Length of time to wait until a connection is opened in seconds
  open_timeout: 100
  # Connections that have not been used in this many seconds will be reset.
  # Sets the idle timeout to idle_timeout. The default timeout is 5 seconds. If you experience “too many connection resets”, reducing this value may help.
  idle_timeout: 500
  # Length of time to wait for data from the server
  read_timeout: 100
  timeout: 100
  user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:12.0) Gecko/20100101 Firefox/12.0"
  # 每页读取多少条记录？这个影响到打开这个页面的速度，
  # 时间太长会超时。所以控制一下。
  mechanize_per_page: 88
  special_agent: 'PSVR_SPECIAL_AGENT_3787fdjihf328DFShze2dfskm894ebkjGFDY'
  proxy:
  # 不使用代理的时候把下面四行注释掉，但是上面这行保留。
     # addr: 192.168.20.6
     # port: 3128
     # user:
     # pass:

sub_cnu: &sub_cnu
  <<: *defaults
  official_website: 'http://www.cnu.edu.cn/'
  uc_appid: '5'
  uc_key: 'af64HZPlY/1RdaOe4UftTp3XO+kQwB9f5SBojhc='
  ktv_sub: 'cnu'
  ktv_subname: '首都师范大学'
  ktv_subname_short: '首师大'
  ktv_subdomain: 'cnu.kejian.tv'
  fotos:
    - 阳光明媚的校本部校门
    - 乌云密布的北一区校门
    - 某次零九级新老生交流会
    - 良乡校区图书馆外
    - 北一区体育馆的二楼乒乓球室
    - 教二楼讨论班小教室
    - 丁浩刚老师在基础物理课上
    - 教二楼一楼阶梯教室的讲台
    - 某次学生会手工厨艺DIY
    - 在北一区文科楼的大阶梯教室上心理学与生活课
    - 数学科学学院张利友教授的板书
    - 王志老师在教四楼上大学英语课
    - 张英伯老师在教二楼上代数课
    - 刘春晓老师在等待上课铃响
  school_new:
    - 2012
    - 9
    - 3
  school_exam:
    - 2013
    - 1
    - 7
  school_over:
    - 2013
    - 1
    - 19
sub_cnu_dev:
  <<: *sub_cnu
  ktv_domain: kejian.lvh.me
  wendao_domain_name: "kejian.lvh.me"
  ktv_subdomain: 'cnu.kejian.lvh.me'
    
sub_ibeike: &sub_ibeike
  <<: *defaults
  official_website: 'http://www.ustb.edu.cn/'
  uc_appid: '11'
  uc_key: '0f4fmuR685V9dnh1d3p/STOCrZ0mElnwrb9S0Q4='
  ktv_sub: 'ibeike'
  ktv_subname: '北京科技大学'
  ktv_subname_short: '北科'
  ktv_subdomain: 'ibeike.kejian.tv'
  fotos:
    - 阳光明媚的北科西校门
    - 沧桑的雪中北科西校门
    - 主楼前的花坛
    - 理化楼的一角
    - 体育场栅栏外的黄昏
    - 夕阳下的宿舍楼
    - 图书馆与众志成城石头
  school_new:
    - 2012
    - 9
    - 10
  school_exam:
    - 2013
    - 1
    - 7
  school_over:
    - 2013
    - 1
    - 21
sub_ibeike_dev:
  <<: *sub_ibeike
  ktv_domain: kejian.lvh.me
  wendao_domain_name: "kejian.lvh.me"
  ktv_subdomain: 'ibeike.kejian.lvh.me'
  
sub_buaa: &sub_buaa
  <<: *defaults
  official_website: 'http://www.buaa.edu.cn/'
  uc_appid: '13'
  uc_key: 'b3c1fXMaji2BCqTHS9v8FC37cLyRnCJyl4pg6wI='
  ktv_sub: 'buaa'
  ktv_subname: '北京航空航天大学'
  ktv_subname_short: '北航'
  ktv_subdomain: 'buaa.kejian.tv'
  fotos:
    - 图书馆与众志成城石头
  school_new:
    - 2012
    - 9
    - 10
  school_exam:
    - 2013
    - 1
    - 7
  school_over:
    - 2013
    - 1
    - 21
sub_buaa_dev:
  <<: *sub_buaa
  ktv_domain: kejian.lvh.me
  wendao_domain_name: "kejian.lvh.me"
  ktv_subdomain: 'buaa.kejian.lvh.me'
