# A sample Guardfile
# More info at https://github.com/guard/guard#readme


guard 'spork', :cucumber => false, :rspec_env => { 'RAILS_ENV' => 'test' } do
  watch('config/application.rb')
  watch('config/environment.rb')
  watch(%r{^config/environments/.+\.rb$})
  watch(%r{^config/initializers/.+\.rb$})
  watch('Gemfile')
  watch('Gemfile.lock')
  watch('spec/spec_helper.rb') { :rspec }
  watch('test/test_helper.rb') { :test_unit }
  watch(%r{features/support/}) { :cucumber }
  watch(%r{^spec/support/(.+)\.rb$})                  { :rspec }
end


guard 'rspec', :version => 2, :cli => '--drb --debug' do
  watch(%r{^spec/.+_spec\.rb$})
  watch(%r{^lib/(.+)\.rb$})     { |m| "spec/lib/#{m[1]}_spec.rb" }
  watch('spec/spec_helper.rb')  { "spec" }

  # Rails example
  watch(%r{^app/controllers/(.+)_(controller)\.rb$})  { |m| "spec/requests/#{m[1]}_spec.rb"}
  watch(%r{^app/views/(.+)/.*\.(erb|haml)$})          { |m| "spec/requests/#{m[1]}_spec.rb" }
  watch(%r{^app/views/cpanel/(.+)/.*\.(erb|haml)$})          { |m| "spec/requests/cpanel_spec.rb" }
  watch('app/controllers/application_controller.rb')  { "spec/requests" }
  watch(%r{^spec/support/(.+)\.rb$})                  { "spec" }

  # Model & Unit Test
  watch(%r{^app/models/(.+)\.rb$})  {|m| "spec/models/#{m[1]}_spec.rb" }
  watch(%r{^app/jobs/(.+)_job\.rb$})  {|m| "spec/jobs/#{m[1]}_spec.rb" }
  watch('app/models/base_model.rb')  { "spec/models" }

end


