# source 'http://ruby.taobao.org/'
source 'https://rubygems.org'

gem 'rails', '3.2.6'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

# MongoDB
gem "mongoid", '<3'
gem "bson_ext"



# Gems used only for assets and not required
# in production environments by default.

#group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
#end
gem 'jquery-rails'
gem "jquery-atwho-rails", ">=0.1.6"
# 禁用 assets 日志
gem 'quiet_assets', ">=1.0.1"
# 分享功能
gem "social-share-button", ">= 0.0.3"
# To use Jbuilder templates for JSON
gem 'jbuilder'


# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

gem 'mongo-rails-instrumentation'
# gem "mongoid-eager-loading","0.3.1"  # deprecated!
# gem "mongoid_rails_migrations", "0.0.10"
# gem "cells","3.6.5"

# gem "dalli","1.1.2"

gem "redis"

# Vote 插件 for Mongoid
gem 'voteable_mongo', path:'vendor/voteable_mongo'

# 分词
gem 'chinese_pinyin'
gem 'rmmseg-cpp-huacnlee'

# 用户系统
# 这个必须锁定版本！！我们定制的太多了
gem 'devise','2.1.0'
gem "omniauth-weibo", :git => 'git://github.com/pmq20/omniauth-weibo.git'
gem "omniauth-renren", :git => 'git://github.com/pmq20/omniauth-renren.git'
gem "omniauth-douban", :git => 'git://github.com/pmq20/omniauth-douban.git'
gem "omniauth-qq", :git => 'git://github.com/pmq20/omniauth-qq.git'
gem "omniauth-google-oauth2"
gem "omniauth-twitter"
gem 'omniauth-facebook'
gem 'omniauth-github'

# 邀请系统
# gem 'devise_invitable'

# 图片上传
gem 'carrierwave', "0.5.3"
# gem 'carrierwave-mongoid', :require => 'carrierwave/mongoid'
gem 'mini_magick'

# 分页
gem 'will_paginate'#,:require=>'will_paginate/array'
gem "will_paginate_mongoid",:path=>'vendor/will_paginate_mongoid'
# gem 'memcache-client', '1.8.5'

# OAuth
# gem 'omniauth', '0.2.0'
# gem "oa-openid", '0.2.0'
# gem "omniauth_china", "0.0.6"

# 后台列表
# gem 'wice_grid', '3.0.0.pre1'

# 设置
gem 'settingslogic'

# 前端优化
# gem 'smurf-huacnlee', :require => "smurf"

# 表单
gem 'simple_form'

# 缓存管理
gem 'tagged-cache'

# PUT 颜色
gem 'colorize'

# 后台表格
# gem 'mongoid_wice_grid', '4.0.0', :require => "wice_grid"

# Crontab 辅助
gem 'whenever'
# AWS SES
# gem "aws-ses", "0.4.2", :require => 'aws/ses'

# Background Jobs
gem "resque", :require => "resque/server", :path => 'vendor/resque'
gem 'resque-pool'
# gem "resque_mailer"

# Comet
# gem "juggernaut"

# Diff 内容并输出 HTML 格式
# gem "htmldiff", :git => "git://github.com/huacnlee/htmldiff.git"

gem "redis-search",:path=>'vendor/redis-search'
gem 'redis-namespace'

group :development do
  gem 'pry'
  gem 'guard-spork'
  gem "rspec-rails"
  # gem 'railroady'
  # gem 'rails-footnotes'
  # gem 'linecache19'
end
gem "letter_opener"


group :test do
  gem 'minitest'
  gem 'turn'
  gem 'pry'
  gem "factory_girl_rails", "~> 1.2"
  gem 'capybara'
  gem 'guard-rspec'
  gem 'rspec-rails'
  gem 'steak'
  # gem 'cucumber-rails'
  # database_cleaner is not required, but highly recommended
  # gem 'database_cleaner'
end


gem 'nokogiri'
gem 'redis-objects'
gem 'progressbar'
gem 'unicorn'
gem 'therubyracer', :platforms => :ruby

gem 'mobile-fu'
gem 'savon'
gem 'rest-client'
gem 'rails_autolink'


gem 'pry-rails'
gem 'pry'

gem 'inherited_resources'
gem "oauth-plugin", ">= 0.4.0.pre1"




gem 'chronic'
gem 'yajl-ruby'

gem 'validate_url', '0.1.6'
gem "redis-objects"
gem 'to_xls', '~> 1.0.0'

gem 'sndacs'
gem 'grim', '>= 0.3.0'
gem 'dalli'

gem 'rails_kindeditor', '~> 0.3.0'
gem 'mechanize', '>=2.5.1'

gem "omnicontacts"
gem 'thin'


gem 'selenium-webdriver'
gem 'debugger'